# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Push with Maven

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: insurance-simulation/backend

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.0.8
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.8
        
    - name: Build with Maven
      run: ./mvnw clean package -f insurance-simulation-backend-parent/pom.xml
      
    - name: Pull JDK image from container-registry.oracle.com
      run: |
        docker login --username ${{ secrets.ORACLE_SSO_USERNAME }} --password ${{ ORACLE_SSO_PASSWORD }} container-registry.oracle.com
        docker pull container-registry.oracle.com/java/jdk:11.0.8
        docker logout container-registry.oracle.com
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
        
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG insurance-simulation-backend-spring
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      
